#############################################################################
# Makefile for building: libTriangleComponent.1.0.0.dylib
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  TriangleComponent.pro
# Template: lib
# Command: /Users/calebbuahin/Qt5.7.0/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile TriangleComponent.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DTRIANGLECOMPONENT_LIBRARY -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -Iinclude -I../HydroCouple/include -I../HydroCoupleSDK/include -I/usr/local -isystem /usr/local/include -I../../../../Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers -I../../../../Qt5.7.0/5.7/clang_64/lib/QtConcurrent.framework/Headers -I../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers -Ibuild/debug/.moc -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../../Qt5.7.0/5.7/clang_64/mkspecs/macx-clang -F/Users/calebbuahin/Qt5.7.0/5.7/clang_64/lib
QMAKE         = /Users/calebbuahin/Qt5.7.0/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = TriangleComponent1.0.0.0
DISTDIR = /Users/calebbuahin/Documents/Projects/HydroCouple/TriangleComponent/build/debug/.obj/TriangleComponent1.0.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/calebbuahin/Qt5.7.0/5.7/clang_64/lib -single_module -dynamiclib -compatibility_version	1.0 -current_version	1.0.0 -install_name	libTriangleComponent.1.dylib
LIBS          = $(SUBLIBS) -F/Users/calebbuahin/Qt5.7.0/5.7/clang_64/lib -L./../HydroCoupleSDK/build/debug -lHydroCoupleSDK -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtConcurrent -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/debug/.obj/

####### Files

SOURCES       = src/stdafx.cpp \
		src/core/triangle.c \
		src/core/tricall.c \
		src/component/trianglecomponent.cpp \
		src/component/trianglecomponentinfo.cpp \
		src/main.cpp build/debug/.moc/moc_trianglecomponent.cpp \
		build/debug/.moc/moc_trianglecomponentinfo.cpp
OBJECTS       = build/debug/.obj/stdafx.o \
		build/debug/.obj/triangle.o \
		build/debug/.obj/tricall.o \
		build/debug/.obj/trianglecomponent.o \
		build/debug/.obj/trianglecomponentinfo.o \
		build/debug/.obj/main.o \
		build/debug/.obj/moc_trianglecomponent.o \
		build/debug/.obj/moc_trianglecomponentinfo.o
DIST          = ../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/qdevice.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/unix.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/mac.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/macx.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/clang.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/qconfig.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/qt.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/resources.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/moc.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/lex.prf \
		TriangleComponent.pro include/stdafx.h \
		include/trianglecomponent_global.h \
		include/core/triangle.h \
		include/component/trianglecomponent.h \
		include/component/trianglecomponentinfo.h src/stdafx.cpp \
		src/core/triangle.c \
		src/core/tricall.c \
		src/component/trianglecomponent.cpp \
		src/component/trianglecomponentinfo.cpp \
		src/main.cpp
QMAKE_TARGET  = TriangleComponent
DESTDIR       = build/debug/
TARGET        = libTriangleComponent.1.0.0.dylib
TARGETA       = build/debug/libTriangleComponent.a
TARGET0       = libTriangleComponent.dylib
TARGETD       = libTriangleComponent.1.0.0.dylib
TARGET1       = libTriangleComponent.1.dylib
TARGET2       = libTriangleComponent.1.0.dylib


first: all
####### Build rules

build/debug/$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@test -d build/debug/ || mkdir -p build/debug/
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)
	-$(DEL_FILE) build/debug/$(TARGET)
	-$(MOVE) $(TARGET)  build/debug/ 
	-$(DEL_FILE) build/debug/$(TARGET0)
	-$(DEL_FILE) build/debug/$(TARGET1)
	-$(DEL_FILE) build/debug/$(TARGET2)
	-$(MOVE) $(TARGET0) build/debug/ 
	-$(MOVE) $(TARGET1) build/debug/ 
	-$(MOVE) $(TARGET2) build/debug/ 



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)
	$(RANLIB) $(TARGETA)

Makefile: TriangleComponent.pro ../../../../Qt5.7.0/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/qdevice.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/unix.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/mac.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/macx.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/clang.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/qconfig.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/qt.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/resources.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/moc.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/lex.prf \
		TriangleComponent.pro \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtConcurrent.framework/QtConcurrent.prl \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile TriangleComponent.pro
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/qdevice.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/device_config.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/unix.conf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/mac.conf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/macx.conf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/sanitize.conf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/clang.conf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/qconfig.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/default_post.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/qt.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/resources.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/moc.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/file_copies.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/yacc.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/lex.prf:
TriangleComponent.pro:
../../../../Qt5.7.0/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
../../../../Qt5.7.0/5.7/clang_64/lib/QtConcurrent.framework/QtConcurrent.prl:
../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile TriangleComponent.pro

qmake_all: FORCE


all: Makefile build/debug/$(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents include/stdafx.h include/trianglecomponent_global.h include/core/triangle.h include/component/trianglecomponent.h include/component/trianglecomponentinfo.h $(DISTDIR)/
	$(COPY_FILE) --parents src/stdafx.cpp src/core/triangle.c src/core/tricall.c src/component/trianglecomponent.cpp src/component/trianglecomponentinfo.cpp src/main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) build/debug/$(TARGET) 
	-$(DEL_FILE) build/debug/$(TARGET0) build/debug/$(TARGET1) build/debug/$(TARGET2) $(TARGETA)
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: build/debug/.moc/moc_trianglecomponent.cpp build/debug/.moc/moc_trianglecomponentinfo.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/debug/.moc/moc_trianglecomponent.cpp build/debug/.moc/moc_trianglecomponentinfo.cpp
build/debug/.moc/moc_trianglecomponent.cpp: include/trianglecomponent_global.h \
		../HydroCoupleSDK/include/core/abstractmodelcomponent.h \
		../HydroCoupleSDK/include/core/identity.h \
		../HydroCoupleSDK/include/core/description.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../HydroCoupleSDK/include/hydrocouplesdk.h \
		../HydroCouple/include/hydrocouple.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QSharedPointer \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qsharedpointer.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QUuid \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/quuid.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QMutex \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdir.h \
		include/core/triangle.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		include/component/trianglecomponent.h \
		../../../../Qt5.7.0/5.7/clang_64/bin/moc
	/Users/calebbuahin/Qt5.7.0/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/calebbuahin/Qt5.7.0/5.7/clang_64/mkspecs/macx-clang -I/Users/calebbuahin/Documents/Projects/HydroCouple/TriangleComponent -I/Users/calebbuahin/Documents/Projects/HydroCouple/TriangleComponent -I/Users/calebbuahin/Documents/Projects/HydroCouple/TriangleComponent/include -I/Users/calebbuahin/Documents/Projects/HydroCouple/HydroCouple/include -I/Users/calebbuahin/Documents/Projects/HydroCouple/HydroCoupleSDK/include -I/usr/local -I/usr/local/include -I/Users/calebbuahin/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/calebbuahin/Qt5.7.0/5.7/clang_64/lib/QtConcurrent.framework/Headers -I/Users/calebbuahin/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.3.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Users/calebbuahin/Qt5.7.0/5.7/clang_64/lib include/component/trianglecomponent.h -o build/debug/.moc/moc_trianglecomponent.cpp

build/debug/.moc/moc_trianglecomponentinfo.cpp: include/trianglecomponent_global.h \
		../HydroCoupleSDK/include/core/modelcomponentinfo.h \
		../HydroCoupleSDK/include/hydrocouplesdk.h \
		../HydroCoupleSDK/include/core/componentinfo.h \
		../HydroCoupleSDK/include/core/identity.h \
		../HydroCoupleSDK/include/core/description.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../HydroCouple/include/hydrocouple.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QSharedPointer \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qsharedpointer.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QUuid \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/quuid.h \
		include/component/trianglecomponentinfo.h \
		../../../../Qt5.7.0/5.7/clang_64/bin/moc
	/Users/calebbuahin/Qt5.7.0/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/calebbuahin/Qt5.7.0/5.7/clang_64/mkspecs/macx-clang -I/Users/calebbuahin/Documents/Projects/HydroCouple/TriangleComponent -I/Users/calebbuahin/Documents/Projects/HydroCouple/TriangleComponent -I/Users/calebbuahin/Documents/Projects/HydroCouple/TriangleComponent/include -I/Users/calebbuahin/Documents/Projects/HydroCouple/HydroCouple/include -I/Users/calebbuahin/Documents/Projects/HydroCouple/HydroCoupleSDK/include -I/usr/local -I/usr/local/include -I/Users/calebbuahin/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/calebbuahin/Qt5.7.0/5.7/clang_64/lib/QtConcurrent.framework/Headers -I/Users/calebbuahin/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.3.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Users/calebbuahin/Qt5.7.0/5.7/clang_64/lib include/component/trianglecomponentinfo.h -o build/debug/.moc/moc_trianglecomponentinfo.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

build/debug/.obj/stdafx.o: src/stdafx.cpp include/stdafx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/stdafx.o src/stdafx.cpp

build/debug/.obj/triangle.o: src/core/triangle.c include/core/triangle.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/triangle.o src/core/triangle.c

build/debug/.obj/tricall.o: src/core/tricall.c include/core/triangle.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/tricall.o src/core/tricall.c

build/debug/.obj/trianglecomponent.o: src/component/trianglecomponent.cpp include/stdafx.h \
		include/component/trianglecomponent.h \
		include/trianglecomponent_global.h \
		../HydroCoupleSDK/include/core/abstractmodelcomponent.h \
		../HydroCoupleSDK/include/core/identity.h \
		../HydroCoupleSDK/include/core/description.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../HydroCoupleSDK/include/hydrocouplesdk.h \
		../HydroCouple/include/hydrocouple.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QSharedPointer \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qsharedpointer.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QUuid \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/quuid.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QMutex \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdir.h \
		include/core/triangle.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		../HydroCoupleSDK/include/core/dimension.h \
		../HydroCoupleSDK/include/core/valuedefinition.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../HydroCoupleSDK/include/core/idbasedargument.h \
		../HydroCoupleSDK/include/core/abstractargument.h \
		../HydroCoupleSDK/include/core/abstractcomponentdataitem.h \
		../HydroCoupleSDK/include/core/idbasedexchangeitems.h \
		../HydroCoupleSDK/include/core/exchangeitems1d.h \
		../HydroCoupleSDK/include/core/abstractinput.h \
		../HydroCoupleSDK/include/core/abstractexchangeitem.h \
		../HydroCoupleSDK/include/core/argument1d.h \
		../HydroCoupleSDK/include/spatial/geometryargument.h \
		../HydroCouple/include/hydrocouplespatial.h \
		../HydroCoupleSDK/include/spatial/point.h \
		../HydroCoupleSDK/include/spatial/geometry.h \
		../HydroCoupleSDK/include/spatial/polyhedralsurface.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../HydroCoupleSDK/include/spatial/polyhedralsurfaceexchangeitem.h \
		../HydroCoupleSDK/include/core/abstractoutput.h \
		../HydroCoupleSDK/include/spatial/polygon.h \
		../HydroCoupleSDK/include/spatial/linestring.h \
		../HydroCoupleSDK/include/spatial/edge.h \
		../HydroCoupleSDK/include/spatial/geometryfactory.h \
		../HydroCoupleSDK/include/spatial/spatialreferencesystem.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtConcurrent.framework/Headers/QtConcurrent \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentcompilertest.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentexception.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilter.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilterkernel.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfunctionwrappers.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentiteratekernel.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmap.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmapkernel.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmedian.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentreducekernel.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrun.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrunbase.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentstoredfunctioncall.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentthreadengine.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/trianglecomponent.o src/component/trianglecomponent.cpp

build/debug/.obj/trianglecomponentinfo.o: src/component/trianglecomponentinfo.cpp include/stdafx.h \
		include/component/trianglecomponentinfo.h \
		include/trianglecomponent_global.h \
		../HydroCoupleSDK/include/core/modelcomponentinfo.h \
		../HydroCoupleSDK/include/hydrocouplesdk.h \
		../HydroCoupleSDK/include/core/componentinfo.h \
		../HydroCoupleSDK/include/core/identity.h \
		../HydroCoupleSDK/include/core/description.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../HydroCouple/include/hydrocouple.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QSharedPointer \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qsharedpointer.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QUuid \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/quuid.h \
		include/component/trianglecomponent.h \
		../HydroCoupleSDK/include/core/abstractmodelcomponent.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QMutex \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdir.h \
		include/core/triangle.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qfileinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/trianglecomponentinfo.o src/component/trianglecomponentinfo.cpp

build/debug/.obj/main.o: src/main.cpp include/stdafx.h \
		include/component/trianglecomponent.h \
		include/trianglecomponent_global.h \
		../HydroCoupleSDK/include/core/abstractmodelcomponent.h \
		../HydroCoupleSDK/include/core/identity.h \
		../HydroCoupleSDK/include/core/description.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../HydroCoupleSDK/include/hydrocouplesdk.h \
		../HydroCouple/include/hydrocouple.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QSharedPointer \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qsharedpointer.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QUuid \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/quuid.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QMutex \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdir.h \
		include/core/triangle.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		../HydroCoupleSDK/include/core/argument1d.h \
		../HydroCoupleSDK/include/core/abstractargument.h \
		../HydroCoupleSDK/include/core/abstractcomponentdataitem.h \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		../../../../Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../HydroCoupleSDK/include/core/exchangeitems1d.h \
		../HydroCoupleSDK/include/core/abstractinput.h \
		../HydroCoupleSDK/include/core/abstractexchangeitem.h \
		../HydroCoupleSDK/include/spatial/geometryargument.h \
		../HydroCouple/include/hydrocouplespatial.h \
		../HydroCoupleSDK/include/spatial/geometryfactory.h \
		../HydroCoupleSDK/include/core/idbasedargument.h \
		../HydroCoupleSDK/include/core/idbasedexchangeitems.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/main.o src/main.cpp

build/debug/.obj/moc_trianglecomponent.o: build/debug/.moc/moc_trianglecomponent.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_trianglecomponent.o build/debug/.moc/moc_trianglecomponent.cpp

build/debug/.obj/moc_trianglecomponentinfo.o: build/debug/.moc/moc_trianglecomponentinfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_trianglecomponentinfo.o build/debug/.moc/moc_trianglecomponentinfo.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

