#ifndef TRIANGLECOMPONENT_GLOBAL_H
#define TRIANGLECOMPONENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRIANGLECOMPONENT_LIBRARY)
#  define TRIANGLECOMPONENT_EXPORT Q_DECL_EXPORT
#else
#  define TRIANGLECOMPONENT_EXPORT Q_DECL_IMPORT
#endif

#endif // TRIANGLECOMPONENT_GLOBAL_H
